.TH "ValOrErrImpl::glue_ValOrErr_from< T, ValOrErr_t, class >" 3 "Sat Nov 21 2020" "ValOrErr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ValOrErrImpl::glue_ValOrErr_from< T, ValOrErr_t, class >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBtype\fP = \fBValOrErr_t\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T, class ValOrErr_t, class = void_t<>>
.br
struct ValOrErrImpl::glue_ValOrErr_from< T, ValOrErr_t, class >"

.PP
Definition at line 85 of file ValOrErr\&.hpp\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<class T , class ValOrErr_t , class  = void_t<>> using \fBValOrErrImpl::glue_ValOrErr_from\fP< T, \fBValOrErr_t\fP, class >::\fBtype\fP =  \fBValOrErr_t\fP"

.PP
Definition at line 86 of file ValOrErr\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ValOrErr from the source code\&.
