.TH "ValOrErrImpl::glue_ValOrErr< ValOrErr_t< variant1, in_place_type_t1, Ret1, Ts... >, ValOrErr_t< variant2, in_place_type_t2, Ret2, Tp... > >" 3 "Sat Nov 21 2020" "ValOrErr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ValOrErrImpl::glue_ValOrErr< ValOrErr_t< variant1, in_place_type_t1, Ret1, Ts... >, ValOrErr_t< variant2, in_place_type_t2, Ret2, Tp... > >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBtype\fP = \fBValOrErr_t\fP< variant1, in_place_type_t1, Ret1, Ts\&.\&.\&., Tp\&.\&.\&. >"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<template< typename\&.\&.\&. > class variant1, template< class > class in_place_type_t1, class Ret1, class \&.\&.\&. Ts, template< typename\&.\&.\&. > class variant2, template< class > class in_place_type_t2, class Ret2, class \&.\&.\&. Tp>
.br
class ValOrErrImpl::glue_ValOrErr< ValOrErr_t< variant1, in_place_type_t1, Ret1, Ts\&.\&.\&. >, ValOrErr_t< variant2, in_place_type_t2, Ret2, Tp\&.\&.\&. > >"

.PP
Definition at line 74 of file ValOrErr\&.hpp\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<template< typename\&.\&.\&. > class variant1, template< class > class in_place_type_t1, class Ret1 , class \&.\&.\&. Ts, template< typename\&.\&.\&. > class variant2, template< class > class in_place_type_t2, class Ret2 , class \&.\&.\&. Tp> using \fBValOrErrImpl::glue_ValOrErr\fP< \fBValOrErr_t\fP< variant1, in_place_type_t1, Ret1, Ts\&.\&.\&. >, \fBValOrErr_t\fP< variant2, in_place_type_t2, Ret2, Tp\&.\&.\&. > >::\fBtype\fP =  \fBValOrErr_t\fP<variant1, in_place_type_t1, Ret1, Ts\&.\&.\&., Tp\&.\&.\&.>"

.PP
Definition at line 77 of file ValOrErr\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ValOrErr from the source code\&.
