.TH "ValOrErrImpl::glue_ValOrErr_from< T, ValOrErr_t, void_t< typename T::ValOrErr_t > >" 3 "Sat Nov 21 2020" "ValOrErr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ValOrErrImpl::glue_ValOrErr_from< T, ValOrErr_t, void_t< typename T::ValOrErr_t > >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBValOrErrImpl::glue_ValOrErr< ValOrErr_t, T::ValOrErr_t >\fP\&.
.SH "Detailed Description"
.PP 

.SS "template<class T, class ValOrErr_t>
.br
struct ValOrErrImpl::glue_ValOrErr_from< T, ValOrErr_t, void_t< typename T::ValOrErr_t > >"

.PP
Definition at line 91 of file ValOrErr\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ValOrErr from the source code\&.
