.TH "ValOrErrImpl::monostate" 3 "Sat Nov 21 2020" "ValOrErr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ValOrErrImpl::monostate
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 22 of file ValOrErr\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ValOrErr from the source code\&.
